- name: Install Nginx
  apt: name=nginx state=present update-cache=yes

- name: create dir /var/www/kibana4
  file: dest=/var/www/kibana4 state=directory

- name: copy template to
  file: src=kibana-reverse-proxy.conf dest=/etc/nginx/sites-enabled/kibana4 state=link

- name: Start nginx service
  service: name=nginx state=started
