---
- hosts: apache
  sudo: yes
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes state=latest
    
    - name: nginx configuration
      template: src=kibana-reverse-proxy.conf.j2 dest=/etc/nginx/sites-enabled/default
      notify:
         - restart nginx
