---
 - name: Install java
   apt: name=openjdk-7-jre state=present update-cache=yes

 - name: Add Elasticsearch apt key.
   apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present
 
 - name: Add Elasticsearch repository.
   apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main'
    state: present
    update_cache: yes

 - name: Install package
   apt: name=elasticsearch state=present update_cache=yes

 - name: Start service
   service: name=elasticsearch state=started
